# Generated by Django 5.0.7 on 2024-08-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_game_tournament_team_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
    ]
