# Generated by Django 5.0.7 on 2024-11-16 01:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_game_date_played_game_score_team1_game_score_team2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email_1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_confirmed', models.BooleanField(default=False)),
                ('conflict_flag', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='tournaments.game')),
                ('result_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to='tournaments.team')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='tournaments.round')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1_matchups', to='tournaments.team')),
                ('team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_2_matchups', to='tournaments.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchups_won', to='tournaments.team')),
            ],
            options={
                'unique_together': {('round', 'team_1'), ('round', 'team_2')},
            },
        ),
        migrations.CreateModel(
            name='Wager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagers', to='tournaments.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagers', to='tournaments.team')),
            ],
            options={
                'unique_together': {('team', 'game')},
            },
        ),
    ]
